name:                transport-types
version:             0.1.0.0
github:              "githubuser/generated-cheops-storage"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/generated-cheops-storage#readme>

ghc-options:
- -Wincomplete-patterns
- -Wall
- -Wno-unused-imports
- -fno-warn-orphans
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints

default-extensions: 
- BangPatterns
- TypeApplications
- DerivingStrategies         
- DerivingVia     
- DeriveGeneric
- DeriveAnyClass          
- GeneralizedNewtypeDeriving  
- OverloadedStrings
- ScopedTypeVariables
- OverloadedLists

dependencies:
- base >= 4.7 && < 5
- quickcheck-instances
- QuickCheck
- scientific
- yaml
- aeson <= 1.5.6.0
- vector
- text
- containers
- unordered-containers
- ghc-prim
- utf8-string
- bytestring
- directory
- generic-random
- hashable
- binary
- swagger2
- lens


library:
  source-dirs: 
    - src
    - external

tests:
   transport-types-test:
    main:                Spec.hs
    source-dirs:         
    - test
    - test/ffi
    - test/test_prototypes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transport-types
    extra-libraries: 
    - c_validate
