resolver: lts-18.17

ghc-options:
  '$everything': -haddock
  
packages:
- .

# extra-lib-dirs:
#   - cbits/c_validate/cmake-build-debug

extra-deps:
- ghc-source-gen-0.4.2.0
- filemanip-0.3.6.3
# - aeson-2.0.2.0
# - OneTuple-0.3.1
# - semialign-1.2.0.1
# - text-short-0.1.4
# - time-compat-1.9.6.1
# - hashable-1.3.5.0
